# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rolf David
title: Theoretical Chemist
email: rolf+david@slmail.me
website: https://cdavro.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  cdavro
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rolf-david-b504b654
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-5338-6267

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=V3R1hVkAAAAJ&hl=en&oi=ao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - **Reactivity**: mechanism, thermodynamics & kinetics 
  - **Condensed** phase & **Interfaces** (Solid Liquid/Liquid-Gas)
  - Solvent / Solutes / Ions **interactions**
  - **Spectroscopies** (IR, vSFG)
  - **Dialogue theory experience** in the field of reactivity and spectroscopy
  - **Machine Learning** for Chemistry (Neural Network-based reactive Force-Fields (**NNP**) & generation of data)
  - **Enhanced Sampling** & Free Energy Calculations
  - Code **development** (Analysis, spectroscopy, AI)
  - Transition Path Sampling (**TPS**)
  - Density Functional Theory (DFT)
  - Molecular Dynamics (MD)
  - Quantum Mechanics/Molecular Mechanics (QM/MM)

content:
  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Post-doctoral researcher at Institut de Biologie Physico-Chimique (Paris, France)
        quote: >
          Since November 2022; Supervisor: Dr. Guillaume Stirnemann
        description: | # this will include new lines to allow paragraphs
          #### Development and uses of Machine Learning for Reactivity
          - Study of **phosphoester bond formation** in aqueous media
          - Use of **AI** for the design of reaction coordinates for complex reactivity
          - **Combined** use of **NNP** and **TPS** to study reactive mechanisms
          - Development of machine learning programs/codes
      - layout: top-middle
        title: Post-doctoral researcher at École Normale Supérieure - Paris Sciences et Lettres (Paris, France)
        quote: >
          2021-2022 (19m); Supervisor: Dr. Damien Laage
        description: | # this will include new lines to allow paragraphs
          #### Simulation of prebiotic chemical reactions catalyzed by aqueous aerosols
          - Study of peptide bond formation in bulk water and at the air-water interface
          - Study of acidity difference between bulk water and air-water interface
          - Development of combined use of NNP and TPS to study reactive mechanisms
          - Development of machine learning and interfaces programs/codes
      - layout: top-middle
        title: Post-doctoral researcher at Louisiana State University (Baton-Rouge, USA)
        quote: >
          2018-2020 (3y); Supervisor: Pr. Revati Kumar
        description: | # this will include new lines to allow paragraphs
          #### Interfaces solid-liquid and their properties: spectroscopy & reactivity
          - Study of the graphene oxide and its properties/reactivity in aqueous media and its spectroscopic signatures (vSFG)
          - Study of peptoids in aqueous media and their micellar structures
          - Study of ion pairing in HCl-water clusters
          - Study of electrolytes in glymes and their non-vehicular diffusion
          - Development of codes for analysis/spectroscopy of sold/liquid and air/water interfaces and new force-fields
      - layout: top-middle
        title: PhD at Université Grenoble-Alpes (Grenoble, France)
        quote: >
          2014-2017 (3y); Supervisor: Pr. Anne Milet, Dr. Yohann Moreau
        description: | # this will include new lines to allow paragraphs
          #### Protonation pathways and reactivity of metalloenzymes
          - Study of a protonation step and reactivity of a metalloenzyme using QM/MM
          - Study of transition metal complexes for catalysis
          - Use of hybrid-DFT/MM and metadynamicsn

  - title: Awards & Distinctions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description:
          - Discussion Leader of the GRS session Chemistry and Physics of Liquids, Holderness, US, August 3-4th 2019
          - Chairman of a PHYS session at the 257th ACS National Meeting “Chemistry for New Frontiers”, Orlando, US, March/April 31-4th, 2019
          - Invited talk at the 257th ACS National Meeting “Chemistry for New Frontiers”, Orlando, US, March/April 31-4th, 2019
          - 1st prize poster at Journée de printemps SCF Rhône-Alpes 2016, Grenoble, FR, June 9th, 2016
          - 1st prize poster at the 7th Modeling Interactions in Biomolecules, Prague, CZ, September 14-18th, 2015


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
